In [7]:
import numpy as np
import cv2 as cv
import glob
 
# termination criteria
criteria = (cv.TERM_CRITERIA_EPS + cv.TERM_CRITERIA_MAX_ITER, 30, 0.001)
 
# prepare object points, like (0,0,0), (1,0,0), (2,0,0) ....,(6,5,0)
objp = np.zeros((6*9,3), np.float32)
objp[:,:2] = np.mgrid[0:9,0:6].T.reshape(-1,2)
 
# Arrays to store object points and image points from all the images.
objpoints = [] # 3d point in real world space
imgpoints = [] # 2d points in image plane.
 
images = glob.glob('*.jpg')
 
for fname in images:
    img = cv.imread(fname)
    gray = cv.cvtColor(img, cv.COLOR_BGR2GRAY)
 
    # Find the chess board corners
    ret, corners = cv.findChessboardCorners(gray, (9,6), None)
 
    # If found, add object points, image points (after refining them)
    if ret == True:
        objpoints.append(objp)
 
        corners2 = cv.cornerSubPix(gray,corners, (11,11), (-1,-1), criteria)
        imgpoints.append(corners2)
 
    # Draw and display the corners
    cv.drawChessboardCorners(img, (9,6), corners2, ret)
    cv.imshow('img', img)
    cv.waitKey(500)
 
cv.destroyAllWindows()

In [10]:
ret, mtx, dist, rvecs, tvecs = cv.calibrateCamera(objpoints, imgpoints, gray.shape[::-1], None, None)

In [11]:
print(ret)

0.09602840355180012


In [12]:
print(mtx)

[[1.43732902e+03 0.00000000e+00 9.18169372e+02]
 [0.00000000e+00 1.43392453e+03 4.98012271e+02]
 [0.00000000e+00 0.00000000e+00 1.00000000e+00]]


In [13]:
print(dist)

[[ 0.04581915 -0.19300152 -0.00258579 -0.00148166  0.15929305]]


In [14]:
print(rvecs)

(array([[ 0.08152177],
       [-0.4450178 ],
       [ 0.00463631]]), array([[ 0.0915969 ],
       [-0.4907986 ],
       [ 0.01283345]]), array([[ 0.0915532 ],
       [-0.49155125],
       [ 0.01315168]]), array([[ 0.08166987],
       [-0.31518788],
       [ 0.01933996]]), array([[-0.03220467],
       [-0.29383851],
       [ 0.00260983]]), array([[ 0.0205415 ],
       [-0.75300422],
       [ 0.01225453]]), array([[ 0.1967437 ],
       [-0.82801817],
       [ 0.17544949]]))


In [15]:
print(tvecs)

(array([[ 1.53770859],
       [ 0.63433305],
       [25.75492686]]), array([[-2.28128318],
       [-0.71970556],
       [24.22037083]]), array([[ 3.5808177 ],
       [-1.37531986],
       [27.29560702]]), array([[ 8.37024195],
       [-1.01213883],
       [26.69605539]]), array([[ 8.77813661],
       [ 4.19630174],
       [27.87559639]]), array([[-11.21132632],
       [  2.13590112],
       [ 22.49925628]]), array([[-9.76446817],
       [-3.6152466 ],
       [20.21724468]]))


In [17]:
np.save("mtx.npy", mtx); np.save("dist.npy", dist)